name: Integration Suite

on: ['push']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  integrate:
    name: Integration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NPM_CONFIG_LOGLEVEL: warn
      WINSTON_CONSOLE_LEVEL: none
      EXPRESS_PORT: 1337

    services:
      mongodb:
        image: mongo:8.0
        env:
          MONGO_INITDB_DATABASE: test
          ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 27017:27017
        options: --health-cmd="mongo" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'

      - name: Installing Dependencies
        run: npm ci

      - name: Compiling Code
        run: npm run build

      - name: Running Tests
        run: npm run cover-ci

      - name: Linting Code
        run: npm run lint